# simple proxy example using traefik single container
# based on https://github.com/BretFisher/dogvscat/blob/master/stack-proxy.yml

version: '3.7'
services:
  traefik:
    image: traefik:1.7-alpine
    networks:
      - proxy
    volumes:
      - acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # traefik dashboard
    command:
      # Use your favourite settings here, but add:
      ## docker settings
      - --docker
      - --docker.swarmMode
      - --docker.domain=traefik
      - --docker.network=proxy
      - --docker.watch
      - --api
      - --defaultentrypoints=http,https
      ## optional letsEncrypt settings
      # - --acme
      # - --acme.email=acme@example.com
      # - --acme.httpchallenge
      # - --acme.httpchallenge.entrypoint=http
      # - --acme.onhostrule=true
      # - --acme.entrypoint=https
      # - --entryPoints=Name:https Address::443 TLS
      # - --entryPoints=Name:http Address::80
      # - --acme.storage=/etc/traefik/acme/acme.json
      # - --acme.acmelogging
      # - --acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      # - --acme.caserver=https://acme-v02.api.letsencrypt.org/directory
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:traefik.example.com # traefik dashboard 
 
volumes:
  acme:

networks:
  proxy:
    driver: overlay
    name: proxy